== Common-io


This module enable to treat content file format and separate this logic from file storage mechanism (except format like PARQUET, where it can't be separated ...).


=== How to use.

First step is to define a configuration class for each schema our module will treat. Most common schema (fixed, csv, excel, json, avro) are already defined on common-io module (each configuration class must implements ContentFormat interface).

Then, defined a global format class that integrate all formats treated by your module, like for FormatConfiguration class.

link:common-io/src/main/java/org/talend/components/common/stream/format/FormatConfiguration.java[format config]



==== Input data.

To define a new input format :

- Define an implementation of RecordReader interface which role is to read an input-stream source.


[source,java]
----
/**
 * Extract an object itrator from stream (reader).
 */
public interface RecordReader extends AutoCloseable {

    /**
     * extract object iterator from reader.
     * 
     * @param reader : stream reader.
     * @return object iterator.
     */
    Iterator<Record> read(InputStream reader);

    @Override
    void close();
}
----

- Define an implemantation of RecordReaderSupplier interface, that is a builder for RecordReader implementation, and register it to format.json file (here, example for json).

link:stream-csv/src/main/resources/TALEND-INF/components/format.json[format declaration]

[source,java]
----
@FunctionalInterface
public interface RecordReaderSupplier {

    RecordReader getReader(RecordBuilderFactory factory, ContentFormat config);

    default RecordReader getReader(RecordBuilderFactory factory, ContentFormat config, Object extraParameter) {
        return this.getReader(factory, config);
    }
}
----


For all already defined format, you just have to add dependencies with corresponding module (stream-json for json format).


- Integration with source.

Find the content format chose by user and get the corresponding record reader :
inject repository with @Service annotation.
[source,java]
----
    @Service
    private final RecordIORepository ioRepository;
----

Then retrieve record reader supplier
[source,java]
----
    ContentFormat format = dataset.....findFormat();
    final RecordReaderSupplier recordReaderSupplier = this.ioRepository.findReader(format.getClass());
    this.recordReader = recordReaderSupplier.getReader(this.factory, format);
----

Then, after getting intputstream instance, return this iterator :

[source,java]
----
    final InputStream in = ...;
    return this.recordReader.read(in);
----

(here, recordReader is integrated in class to allow to close it at the end, it's not mandatory)


==== Output Data

- Define an implementation of RecordWriter interface which role is to read an input-stream source.

- Define an implementation of RecordWriterSupplier and register an instance to RecordWriterRepository
like with this json class.

[source,java]
----
include::./stream-json/src/main/java/org/talend/components/common/stream/output/json/JsonWriterSupplier.java[]
----

declare it to format.json file

- For Writer, step are similar to reader :

then use writer in tacokit method :
[source,java]
----
@AfterGroup
public void write(final Collection<Record> records) {
    try {
        if (this.recordWriter != null) {
            this.recordWriter.add(records);
            this.recordWriter.flush();
        }
----

