FROM bitnami/rabbitmq:latest
#RUN mkdir -p /bitnami/rabbitmq/certificates
#COPY /certificates /bitnami/rabbitmq/certificates/
#COPY server_certificate.pem /bitnami/rabbitmq/conf/
#COPY server_key.pem /bitnami/rabbitmq/conf/
USER root
COPY /bitnami /bitnami/
#COPY /conf/rabbitmq.config /bitnami/rabbitmq/conf/rabbitmq.config
#RUN ls -al /bitnami/rabbitmq/conf/rabbitmq.config
#&& chmod 777 /bitnami/rabbitmq/conf/rabbitmq.config
#RUN rm -rf /bitnami/rabbitmq/conf/rabbitmq.config
