package org.talend.components.jdbc.configuration;

import lombok.Data;
import org.talend.sdk.component.api.configuration.Option;
import org.talend.sdk.component.api.configuration.ui.layout.GridLayout;
import org.talend.sdk.component.api.meta.Documentation;

import java.io.Serializable;

import static org.talend.sdk.component.api.configuration.ui.layout.GridLayout.FormType.ADVANCED;

@Data
@GridLayout(names = ADVANCED, value = { @GridLayout.Row("fetchSize") })
@Documentation("Advanced common input configuration")
public class InputAdvancedCommonConfig implements Serializable {

    @Option
    @Documentation("Gives the JDBC driver a hint as to the number of rows that should be fetched from "
            + "the database when more rows are needed for ResultSet objects generated by this Statement.\n"
            + "If the value specified is zero, then the hint is ignored.")
    private int fetchSize = 0;

}
